import { StyleSheet } from "react-native";
import { Colors, Radius, Shadows, Spacing, Type } from "@/config/theme";
export const ratingStyles = StyleSheet.create({
    screen: { flex: 1, backgroundColor: Colors.background },
    scroll: {
        paddingHorizontal: Spacing.xl,
        alignItems: "center",
        paddingBottom: Spacing.xxl,
    },
    avatar: {
        width: 88,
        height: 88,
        borderRadius: 44,
        backgroundColor: Colors.primaryMuted,
        alignItems: "center",
        justifyContent: "center",
        marginBottom: Spacing.lg,
        ...Shadows.floatSm,
    },
    title: { ...Type.h1, textAlign: "center", marginTop: Spacing.sm },
    sub: {
        marginTop: Spacing.sm,
        fontSize: 15,
        color: Colors.textSecondary,
        textAlign: "center",
    },
    starsWrap: {
        marginTop: Spacing.lg,
        borderWidth: 1,
        borderColor: "transparent",
        borderRadius: Radius.lg,
        paddingVertical: Spacing.xs,
        paddingHorizontal: Spacing.sm,
    },
    starsWrapError: { borderColor: "transparent" },
    tagLabel: {
        alignSelf: "center",
        marginTop: Spacing.lg,
        fontSize: 18,
        color: Colors.text,
        marginBottom: Spacing.sm,
        fontWeight: "600",
    },
    loadText: { color: Colors.textSecondary, fontSize: 13, marginTop: Spacing.sm },
    commentInput: {
        width: "100%",
        minHeight: 110,
        marginTop: Spacing.md,
        borderWidth: 1,
        borderColor: Colors.border,
        borderRadius: Radius.lg,
        paddingHorizontal: Spacing.md,
        paddingVertical: Spacing.md,
        color: Colors.text,
        fontSize: 14,
        textAlignVertical: "top",
        backgroundColor: Colors.surfaceElevated,
    },
    commentCount: {
        width: "100%",
        marginTop: Spacing.xs,
        textAlign: "right",
        fontSize: 12,
        color: Colors.textMuted,
    },
    footer: { paddingHorizontal: Spacing.lg, gap: Spacing.sm, paddingTop: Spacing.md },
    celebrateOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: Colors.celebrateScrim,
        alignItems: "center",
        justifyContent: "center",
        zIndex: 40,
    },
});
