import { StyleSheet } from "react-native";
import { Colors, Radius, Shadows, Spacing, Type } from "@/config/theme";
export const orderFareStyles = StyleSheet.create({
    screen: { flex: 1, backgroundColor: Colors.background, paddingHorizontal: Spacing.lg },
    headerRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: Spacing.lg,
    },
    headerSideSpacer: { width: 24 },
    headerTitle: { ...Type.h2, fontSize: 28, fontWeight: "800" },
    scroll: { gap: Spacing.lg },
    payableBlock: {
        alignItems: "center",
        paddingVertical: Spacing.sm,
    },
    payableLabel: {
        fontSize: 16,
        color: Colors.textSecondary,
        fontWeight: "600",
    },
    payableValue: {
        marginTop: Spacing.xs,
        fontSize: 44,
        fontWeight: "800",
        color: Colors.primary,
    },
    breakdownCard: {
        backgroundColor: Colors.surfaceElevated,
        borderWidth: 1,
        borderColor: Colors.border,
        borderRadius: Radius.xl,
        padding: Spacing.lg,
    },
    breakdownHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    breakdownTitle: { fontSize: 20, fontWeight: "800", color: Colors.text },
    breakdownRows: { marginTop: Spacing.md, gap: Spacing.sm },
    breakdownRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    breakdownKey: { color: Colors.textSecondary, fontSize: 17, fontWeight: "500" },
    breakdownValue: { color: Colors.text, fontSize: 18, fontWeight: "600" },
    breakdownValueStrong: { fontWeight: "800" },
    sectionLabel: {
        textAlign: "center",
        fontSize: 20,
        fontWeight: "800",
        color: Colors.text,
        marginTop: Spacing.sm,
    },
    payStack: { gap: Spacing.md },
    paymentCard: {
        flexDirection: "row",
        alignItems: "center",
        gap: Spacing.md,
        backgroundColor: Colors.surfaceElevated,
        borderWidth: 1,
        borderColor: Colors.border,
        borderRadius: Radius.xl,
        padding: Spacing.md,
        ...Shadows.floatSm,
    },
    paymentIconWrap: {
        width: 48,
        height: 48,
        borderRadius: 14,
        backgroundColor: Colors.primaryMuted,
        alignItems: "center",
        justifyContent: "center",
    },
    paymentTitle: { fontSize: 20, color: Colors.text, fontWeight: "800" },
    paymentSub: { fontSize: 14, color: Colors.textSecondary, marginTop: 2 },
    paymentTextColumn: { flex: 1 },
    noMethods: { fontSize: 14, color: Colors.textSecondary, fontWeight: "600" },
    centered: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        gap: Spacing.md,
    },
    loadingText: { color: Colors.textSecondary, fontWeight: "600" },
    errorBlock: { flex: 1, justifyContent: "center", gap: Spacing.lg },
    retryBtn: { alignSelf: "stretch" },
});
