import { StyleSheet } from "react-native";
import { Colors, Radius, Shadows, Spacing, Type } from "@/config/theme";
export const tripHistoryStyles = StyleSheet.create({
    screen: { flex: 1, backgroundColor: Colors.background },
    header: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: Spacing.md,
        paddingVertical: Spacing.md,
    },
    headerTitle: { ...Type.h2 },
    headerRightSpacer: { width: 26 },
    hairline: { height: StyleSheet.hairlineWidth, backgroundColor: Colors.border },
    tabs: {
        flexDirection: "row",
        gap: Spacing.sm,
        paddingHorizontal: Spacing.lg,
        paddingVertical: Spacing.md,
    },
    tab: {
        paddingVertical: Spacing.sm,
        paddingHorizontal: Spacing.md,
        borderRadius: Radius.full,
        backgroundColor: Colors.surface,
    },
    tabActive: { backgroundColor: Colors.primary },
    tabText: { fontSize: 13, fontWeight: "700", color: Colors.textSecondary },
    tabTextActive: { color: Colors.white },
    list: { padding: Spacing.lg, paddingBottom: Spacing.xl, gap: Spacing.md },
    card: {
        borderWidth: 1,
        borderColor: Colors.border,
        borderRadius: Radius.xl,
        padding: Spacing.md + 2,
        backgroundColor: Colors.surfaceElevated,
        ...Shadows.floatSm,
    },
    cardTop: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    dateRow: { flexDirection: "row", alignItems: "center", gap: 6 },
    dateText: { fontSize: 13, color: Colors.textSecondary, fontWeight: "600" },
    statusPill: {
        backgroundColor: Colors.primarySoft,
        paddingHorizontal: Spacing.sm,
        paddingVertical: 4,
        borderRadius: Radius.full,
    },
    statusText: { fontSize: 12, fontWeight: "700", color: Colors.primaryDark },
    route: { flexDirection: "row", gap: Spacing.md, marginTop: Spacing.md },
    timeline: { alignItems: "center", width: 16 },
    dot: { width: 10, height: 10, borderRadius: 5 },
    dotPickup: { backgroundColor: Colors.primary },
    dotDrop: { backgroundColor: Colors.danger },
    vline: {
        width: 2,
        flex: 1,
        minHeight: 28,
        backgroundColor: Colors.border,
        marginVertical: 4,
    },
    placesColumn: { flex: 1 },
    place: { fontSize: 15, fontWeight: "700", color: Colors.text },
    dropPlace: { marginTop: Spacing.lg },
    hairlineCard: {
        height: StyleSheet.hairlineWidth,
        backgroundColor: Colors.border,
        marginVertical: Spacing.md,
    },
    cardBottom: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    payPill: {
        paddingHorizontal: Spacing.sm,
        paddingVertical: 4,
        borderRadius: Radius.full,
    },
    payOnline: { backgroundColor: Colors.primarySoft },
    payCash: { backgroundColor: "#FFEDD5" },
    payText: { fontSize: 12, fontWeight: "700", color: Colors.primaryDark },
    payTextCash: { color: "#C2410C" },
    fareRow: { flexDirection: "row", alignItems: "center", gap: 4 },
    fare: { fontSize: 18, fontWeight: "800", color: Colors.text },
});
