import { StyleSheet } from "react-native";
import { Colors, Radius, Shadows, Spacing } from "@/config/theme";
export const styles = StyleSheet.create({
    screen: { flex: 1, backgroundColor: Colors.background },
    menuBtn: {
        position: "absolute",
        left: Spacing.md,
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: Colors.surfaceElevated,
        alignItems: "center",
        justifyContent: "center",
        zIndex: 2,
        ...Shadows.floatMd,
    },
    flex1: { flex: 1 },
    blockBanner: {
        position: "absolute",
        left: Spacing.lg,
        right: Spacing.lg,
        zIndex: 3,
        flexDirection: "row",
        alignItems: "center",
        gap: Spacing.sm,
        borderRadius: Radius.lg,
        backgroundColor: Colors.warningSoft,
        borderWidth: 1,
        borderColor: Colors.warning,
        paddingHorizontal: Spacing.md,
        paddingVertical: Spacing.sm,
        ...Shadows.floatSm,
    },
    blockText: {
        flex: 1,
        color: Colors.text,
        fontSize: 12.5,
        fontWeight: "600",
    },
    blockCard: {
        position: "absolute",
        left: Spacing.lg,
        right: Spacing.lg,
        zIndex: 2,
        backgroundColor: Colors.surfaceElevated,
        borderWidth: 1,
        borderColor: Colors.warning,
        borderRadius: Radius.xl,
        padding: Spacing.md,
        gap: Spacing.sm,
        ...Shadows.floatMd,
    },
    blockCardTitle: {
        color: Colors.text,
        fontSize: 15,
        fontWeight: "800",
    },
    blockCardReason: {
        color: Colors.textSecondary,
        fontSize: 13,
        lineHeight: 20,
    },
    summaryWrap: {
        position: "absolute",
        left: Spacing.lg,
        right: Spacing.lg,
        backgroundColor: Colors.surfaceElevated,
        borderRadius: Radius.xxl,
        padding: Spacing.lg,
        zIndex: 1,
        ...Shadows.floatMd,
    },
    summaryTitle: {
        fontSize: 17,
        fontWeight: "800",
        color: Colors.text,
        marginBottom: Spacing.md,
    },
    grid: { flexDirection: "row", flexWrap: "wrap", gap: Spacing.sm },
    tile: {
        width: "48%",
        flexGrow: 1,
        backgroundColor: Colors.surface,
        borderRadius: Radius.md,
        padding: Spacing.md,
    },
    tileHighlight: { backgroundColor: Colors.primarySoft },
    tileRupee: { fontSize: 16, fontWeight: "800", color: Colors.primary },
    tileLabel: { fontSize: 12, color: Colors.textSecondary, marginTop: 4 },
    tileValue: {
        fontSize: 20,
        fontWeight: "800",
        color: Colors.text,
        marginTop: 2,
    },
    compactCard: {
        position: "absolute",
        left: Spacing.lg,
        right: Spacing.lg,
        flexDirection: "row",
        backgroundColor: Colors.surfaceElevated,
        borderRadius: Radius.xxl,
        padding: Spacing.md + 2,
        justifyContent: "space-between",
        zIndex: 1,
        ...Shadows.floatMd,
    },
    compactLeft: { flexDirection: "row", alignItems: "center", gap: Spacing.sm },
    compactRight: { flexDirection: "row", alignItems: "center", gap: Spacing.sm },
    miniIcon: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: Colors.primarySoft,
        alignItems: "center",
        justifyContent: "center",
    },
    rupee: { fontSize: 18, fontWeight: "800", color: Colors.primaryDark },
    compactLabel: { fontSize: 12, color: Colors.textSecondary },
    compactValue: { fontSize: 18, fontWeight: "800", color: Colors.text },
    searchingWrap: {
        ...StyleSheet.absoluteFillObject,
        alignItems: "center",
        justifyContent: "center",
        zIndex: 0,
    },
    searchRing: {
        position: "absolute",
        borderWidth: 2,
        borderColor: Colors.mapPulseRing,
    },
    searchRingInner: {
        width: 168,
        height: 168,
        borderRadius: 84,
    },
    searchRingMid: {
        width: 224,
        height: 224,
        borderRadius: 112,
        borderWidth: 1.5,
    },
    searchRingOuter: {
        width: 288,
        height: 288,
        borderRadius: 144,
        borderWidth: 1,
    },
    radarCore: {
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: Colors.primary,
        alignItems: "center",
        justifyContent: "center",
        ...Shadows.floatSm,
    },
    searchingText: {
        marginTop: Spacing.lg,
        fontSize: 16,
        color: Colors.textSecondary,
        fontWeight: "600",
        textAlign: "center",
        paddingHorizontal: Spacing.lg,
    },
    shimmerTrack: {
        marginTop: Spacing.md,
        width: 200,
        height: 4,
        borderRadius: 2,
        backgroundColor: Colors.shimmerBase,
        overflow: "hidden",
    },
    shimmerBar: {
        width: 72,
        height: 4,
        borderRadius: 2,
        backgroundColor: Colors.shimmerHighlight,
    },
    bottom: {
        position: "absolute",
        left: Spacing.lg,
        right: Spacing.lg,
        bottom: 0,
        alignItems: "stretch",
        zIndex: 4,
    },
    offlineLabel: {
        fontSize: 16,
        color: Colors.textSecondary,
        marginBottom: Spacing.md,
        textAlign: "center",
        alignSelf: "center",
    },
    onlineLabelRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: Spacing.sm,
        marginBottom: Spacing.md,
        flexWrap: "wrap",
        alignSelf: "center",
    },
    onlineLabel: { fontSize: 16, color: Colors.primary, fontWeight: "700" },
    socketLive: { fontSize: 13, fontWeight: "700", color: Colors.primary },
    socketPending: {
        fontSize: 13,
        fontWeight: "600",
        color: Colors.textSecondary,
    },
    socketError: { fontSize: 13, fontWeight: "600", color: Colors.danger },
    offerBackdrop: {
        flex: 1,
        backgroundColor: Colors.overlay,
        justifyContent: "flex-end",
    },
    offerSheet: {
        backgroundColor: Colors.surfaceElevated,
        borderTopLeftRadius: Radius.xxl,
        borderTopRightRadius: Radius.xxl,
        padding: Spacing.lg,
        paddingBottom: Spacing.xl,
        ...Shadows.sheetTop,
    },
    offerHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    offerTitle: { fontSize: 20, fontWeight: "800", color: Colors.text },
    timerBadge: {
        backgroundColor: Colors.timerPink,
        paddingHorizontal: 12,
        paddingVertical: 5,
        borderRadius: Radius.full,
    },
    timerText: { fontWeight: "800", color: Colors.timerRed, fontSize: 13 },
    warnBanner: {
        marginTop: Spacing.md,
        flexDirection: "row",
        alignItems: "center",
        gap: Spacing.sm,
        backgroundColor: Colors.helperBannerBg,
        borderWidth: 1,
        borderColor: Colors.helperBannerBorder,
        padding: Spacing.md,
        borderRadius: Radius.lg,
    },
    warnText: {
        flex: 1,
        fontSize: 14,
        fontWeight: "600",
        color: Colors.helperBannerText,
    },
    customerName: {
        marginTop: Spacing.md,
        fontSize: 14,
        fontWeight: "600",
        color: Colors.textSecondary,
    },
    route: { marginTop: Spacing.lg },
    routeRow: { flexDirection: "row", gap: Spacing.md },
    routeDotOuter: {
        width: 18,
        height: 18,
        borderRadius: 9,
        alignItems: "center",
        justifyContent: "center",
        marginTop: 4,
    },
    routeDotPickup: { backgroundColor: Colors.primary },
    routeDotDrop: { backgroundColor: Colors.danger },
    routeDotInner: {
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: Colors.white,
    },
    dotted: {
        width: 2,
        height: 20,
        borderLeftWidth: 2,
        borderStyle: "dashed",
        borderColor: Colors.border,
        marginLeft: 4,
        marginVertical: 4,
    },
    routeLabel: { fontSize: 11, color: Colors.textSecondary, fontWeight: "700" },
    routePlace: { fontSize: 16, fontWeight: "800", color: Colors.text },
    routeMeta: { fontSize: 13, color: Colors.textSecondary, marginTop: 2 },
    fareBar: {
        marginTop: Spacing.lg,
        backgroundColor: Colors.primarySoft,
        borderRadius: Radius.lg,
        padding: Spacing.md + 2,
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    fareLabel: { fontSize: 14, color: Colors.textSecondary, fontWeight: "600" },
    fareAmt: { fontSize: 22, fontWeight: "800", color: Colors.primaryDark },
    offerActions: {
        flexDirection: "row",
        gap: Spacing.md,
        marginTop: Spacing.lg,
    },
});
