import { StyleSheet } from "react-native";
import { Colors, Radius, Shadows, Spacing, Type } from "@/config/theme";
export const cashPaymentStyles = StyleSheet.create({
    screen: {
        flex: 1,
        backgroundColor: Colors.background,
        paddingHorizontal: Spacing.lg,
    },
    headerRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: Spacing.lg,
    },
    headerSideSpacer: { width: 24 },
    header: { ...Type.h2 },
    payableBlock: {
        alignItems: "center",
        marginBottom: Spacing.md,
    },
    payableLabel: { fontSize: 15, color: Colors.textSecondary, fontWeight: "600" },
    payableValue: {
        marginTop: Spacing.xs,
        fontSize: 40,
        fontWeight: "800",
        color: Colors.primary,
    },
    breakdownCard: {
        borderRadius: Radius.xl,
        borderWidth: 1,
        borderColor: Colors.border,
        backgroundColor: Colors.surfaceElevated,
        padding: Spacing.md,
        marginBottom: Spacing.md,
    },
    breakdownHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    breakdownTitle: { fontSize: 16, fontWeight: "800", color: Colors.text },
    breakdownRows: { marginTop: Spacing.sm, gap: Spacing.xs },
    breakdownRow: {
        flexDirection: "row",
        justifyContent: "space-between",
    },
    breakdownKey: { fontSize: 14, color: Colors.textSecondary },
    breakdownValue: { fontSize: 14, color: Colors.text, fontWeight: "600" },
    card: {
        borderRadius: Radius.xl,
        borderWidth: 1,
        borderColor: Colors.border,
        backgroundColor: Colors.surfaceElevated,
        padding: Spacing.lg,
        alignItems: "center",
        ...Shadows.floatSm,
    },
    iconWrap: {
        width: 72,
        height: 72,
        borderRadius: Radius.lg,
        backgroundColor: Colors.primaryMuted,
        alignItems: "center",
        justifyContent: "center",
        marginBottom: Spacing.md,
    },
    amountLabel: {
        fontSize: 30,
        color: Colors.text,
        fontWeight: "800",
        marginTop: Spacing.sm,
    },
    sub: {
        marginTop: Spacing.md,
        textAlign: "center",
        color: Colors.textSecondary,
        fontSize: 14,
        lineHeight: 20,
    },
    error: {
        marginTop: Spacing.sm,
        color: Colors.danger,
        fontSize: 13,
        fontWeight: "600",
        textAlign: "center",
    },
    footer: { marginTop: "auto" },
    modalBackdrop: {
        flex: 1,
        backgroundColor: Colors.overlay,
        justifyContent: "flex-end",
        padding: Spacing.lg,
    },
    modalCard: {
        backgroundColor: Colors.surfaceElevated,
        borderRadius: Radius.xl,
        borderWidth: 1,
        borderColor: Colors.border,
        padding: Spacing.lg,
        ...Shadows.sheetTop,
    },
    modalTitle: { ...Type.h2 },
    modalSub: {
        marginTop: Spacing.sm,
        color: Colors.textSecondary,
        fontSize: 14,
        lineHeight: 20,
    },
    modalSubStrong: { fontWeight: "800" },
    modalActions: {
        marginTop: Spacing.lg,
        flexDirection: "row",
        gap: Spacing.md,
    },
    modalBtnFlex: { flex: 1 },
    confirmBtn: { flex: 1 },
});
