import { StyleSheet } from "react-native";
import { Colors, Radius, Shadows, Spacing, Type } from "@/config/theme";
export const permissionsStyles = StyleSheet.create({
    screen: { flex: 1, backgroundColor: Colors.background },
    scroll: { paddingHorizontal: Spacing.lg, paddingBottom: Spacing.xl },
    lockWrap: {
        alignSelf: "center",
        width: 64,
        height: 64,
        borderRadius: Radius.lg,
        backgroundColor: Colors.primaryMuted,
        alignItems: "center",
        justifyContent: "center",
        marginBottom: Spacing.md,
        ...Shadows.floatSm,
    },
    lockEmoji: { fontSize: 32 },
    title: { ...Type.h1, fontSize: 24, textAlign: "center" },
    subtitle: {
        marginTop: Spacing.sm,
        fontSize: 15,
        color: Colors.textSecondary,
        textAlign: "center",
        marginBottom: Spacing.lg,
        lineHeight: 22,
    },
    card: {
        flexDirection: "row",
        gap: Spacing.md,
        borderWidth: 1,
        borderColor: Colors.border,
        borderRadius: Radius.xl,
        padding: Spacing.md + 2,
        marginBottom: Spacing.md,
        alignItems: "center",
        backgroundColor: Colors.surfaceElevated,
        ...Shadows.floatSm,
    },
    iconCircle: {
        width: 48,
        height: 48,
        borderRadius: 24,
        alignItems: "center",
        justifyContent: "center",
    },
    cardTextColumn: { flex: 1 },
    cardTitle: { fontSize: 16, fontWeight: "700", color: Colors.text },
    cardDesc: {
        marginTop: 4,
        fontSize: 14,
        color: Colors.textSecondary,
        lineHeight: 20,
    },
    footerNote: {
        fontSize: 13,
        color: Colors.textSecondary,
        textAlign: "center",
        marginTop: Spacing.md,
        lineHeight: 18,
    },
    settingsHint: {
        marginTop: Spacing.sm,
        color: Colors.danger,
        textAlign: "center",
        fontSize: 13,
        fontWeight: "600",
    },
    platformNote: {
        marginTop: Spacing.sm,
        color: Colors.textMuted,
        textAlign: "center",
        fontSize: 12,
    },
    statusWrap: {
        minWidth: 82,
        alignItems: "center",
        justifyContent: "center",
        gap: 2,
    },
    statusText: {
        fontSize: 11,
        fontWeight: "700",
    },
    bottom: { paddingHorizontal: Spacing.lg, gap: Spacing.sm },
    secondaryBtn: {
        backgroundColor: Colors.surfaceElevated,
    },
});
