import { StyleSheet } from "react-native";
import { Colors, Radius, Shadows, Spacing } from "@/config/theme";
export const styles = StyleSheet.create({
    screen: { flex: 1, backgroundColor: Colors.background },
    flex1: { flex: 1 },
    mapSection: {
        height: "45%",
        minHeight: 260,
        borderBottomLeftRadius: Radius.lg,
        borderBottomRightRadius: Radius.lg,
        overflow: "hidden",
        backgroundColor: Colors.surface,
    },
    mapFill: { flex: 1 },
    mapChrome: {
        ...StyleSheet.absoluteFillObject,
        zIndex: 4,
    },
    detailScroll: {
        flex: 1,
        backgroundColor: Colors.background,
    },
    detailContent: {
        paddingHorizontal: Spacing.lg,
        paddingTop: Spacing.md,
        gap: Spacing.md,
    },
    statusPill: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        backgroundColor: Colors.surfaceElevated,
        borderRadius: Radius.lg,
        paddingVertical: Spacing.md,
        paddingHorizontal: Spacing.lg,
        borderWidth: StyleSheet.hairlineWidth,
        borderColor: Colors.border,
        ...Shadows.floatSm,
    },
    statusPillPrimary: {
        backgroundColor: Colors.primary,
        borderColor: Colors.primary,
    },
    statusPillText: {
        flex: 1,
        fontWeight: "800",
        color: Colors.text,
        fontSize: 15,
    },
    statusPillTextInverse: { color: Colors.white },
    waitBadgeOnPrimary: { backgroundColor: Colors.onPrimaryMuted },
    sos: {
        position: "absolute",
        left: Spacing.md,
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: Colors.danger,
        alignItems: "center",
        justifyContent: "center",
        zIndex: 3,
        ...Shadows.floatSm,
    },
    more: {
        position: "absolute",
        right: Spacing.md,
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: Colors.surfaceElevated,
        alignItems: "center",
        justifyContent: "center",
        zIndex: 3,
        ...Shadows.floatSm,
    },
    menuCard: {
        position: "absolute",
        right: Spacing.md,
        width: 170,
        backgroundColor: Colors.surfaceElevated,
        borderRadius: Radius.md,
        borderWidth: 1,
        borderColor: Colors.border,
        paddingVertical: Spacing.xs,
        ...Shadows.floatLg,
    },
    menuItem: {
        flexDirection: "row",
        alignItems: "center",
        gap: Spacing.sm,
        paddingHorizontal: Spacing.md,
        paddingVertical: Spacing.sm,
    },
    menuItemText: { color: Colors.danger, fontWeight: "700", fontSize: 14 },
    waitBadge: {
        flexDirection: "row",
        alignItems: "center",
        gap: 4,
        backgroundColor: Colors.warningSoft,
        paddingHorizontal: Spacing.sm,
        paddingVertical: 4,
        borderRadius: Radius.full,
    },
    waitBadgeText: { fontSize: 12, fontWeight: "700", color: Colors.warning },
    profileRow: { flexDirection: "row", alignItems: "center", gap: Spacing.md },
    avatar: {
        width: 52,
        height: 52,
        borderRadius: 26,
        backgroundColor: Colors.surface,
        alignItems: "center",
        justifyContent: "center",
        borderWidth: StyleSheet.hairlineWidth,
        borderColor: Colors.border,
    },
    name: { fontSize: 18, fontWeight: "800", color: Colors.text },
    role: { fontSize: 13, color: Colors.textSecondary, marginTop: 2 },
    call: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: Colors.primary,
        alignItems: "center",
        justifyContent: "center",
    },
    metaRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
        marginTop: Spacing.sm,
    },
    metaText: { fontSize: 13, fontWeight: "600", color: Colors.textSecondary },
    metaDot: { color: Colors.textMuted },
    locBox: {
        flexDirection: "row",
        gap: Spacing.md,
        backgroundColor: Colors.surface,
        borderRadius: Radius.md,
        padding: Spacing.md,
        alignItems: "center",
        marginTop: Spacing.md,
    },
    addr: { fontSize: 16, fontWeight: "800", color: Colors.text },
    addrSub: { fontSize: 13, color: Colors.textSecondary, marginTop: 2 },
    navBtn: { marginBottom: 0 },
    otpHint: { textAlign: "center", color: Colors.textSecondary, fontSize: 14 },
    otpPanel: {
        backgroundColor: Colors.surface,
        borderRadius: Radius.lg,
        borderWidth: 1,
        borderColor: Colors.border,
        padding: Spacing.md,
        gap: Spacing.sm,
        ...Shadows.floatSm,
    },
    otpTitle: {
        textAlign: "center",
        color: Colors.text,
        fontWeight: "800",
        fontSize: 16,
    },
    demoOtp: {
        textAlign: "center",
        fontSize: 13,
        color: Colors.textSecondary,
        marginTop: Spacing.sm,
        lineHeight: 18,
    },
    bottomActionPad: {
        marginBottom: Spacing.md,
    },
    errorBanner: {
        backgroundColor: Colors.dangerSoft,
        borderRadius: Radius.md,
        padding: Spacing.md,
        borderWidth: 1,
        borderColor: Colors.danger,
    },
    errorBannerText: { color: Colors.danger, fontWeight: "600", fontSize: 13 },
    modalBackdrop: {
        flex: 1,
        backgroundColor: Colors.overlay,
        justifyContent: "flex-end",
        padding: Spacing.lg,
    },
    modalCard: {
        backgroundColor: Colors.surfaceElevated,
        borderRadius: Radius.xl,
        padding: Spacing.lg,
        borderWidth: 1,
        borderColor: Colors.border,
        ...Shadows.sheetTop,
    },
    modalTitle: { color: Colors.text, fontSize: 18, fontWeight: "800" },
    modalSub: {
        color: Colors.textSecondary,
        fontSize: 14,
        marginTop: Spacing.sm,
        lineHeight: 20,
    },
    modalHint: {
        marginTop: Spacing.sm,
        marginBottom: Spacing.sm,
        color: Colors.textSecondary,
        fontSize: 13,
    },
    modalActions: {
        flexDirection: "row",
        gap: Spacing.md,
        marginTop: Spacing.lg,
    },
    dangerButton: {
        flex: 1,
        backgroundColor: Colors.danger,
        borderColor: Colors.danger,
    },
});
