import { StyleSheet } from "react-native";
import { Colors, Radius, Shadows, Spacing } from "@/config/theme";

export const styles = StyleSheet.create({
    screen: { flex: 1, backgroundColor: Colors.background },
    scroll: { paddingHorizontal: Spacing.lg, paddingBottom: Spacing.xl },
    fieldLabel: { fontSize: 14, fontWeight: "600", color: Colors.text },
    req: { color: Colors.danger },
    toggleRow: { flexDirection: "row", gap: Spacing.md, marginTop: Spacing.sm },
    toggleCard: {
        flex: 1,
        borderWidth: 1,
        borderColor: Colors.border,
        borderRadius: Radius.lg,
        padding: Spacing.md,
        flexDirection: "row",
        alignItems: "center",
        gap: Spacing.sm,
        backgroundColor: Colors.surfaceElevated,
        ...Shadows.floatSm,
    },
    toggleActive: {
        borderColor: Colors.primary,
        backgroundColor: Colors.primarySoft,
    },
    radio: {
        width: 20,
        height: 20,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: Colors.border,
    },
    radioOn: { borderColor: Colors.primary, backgroundColor: Colors.primary },
    radioOnInner: {
        borderColor: Colors.primary,
        backgroundColor: Colors.primary,
    },
    toggleText: { fontSize: 16, fontWeight: "600", color: Colors.text },
    input: {
        marginTop: Spacing.sm,
        borderWidth: 1,
        borderColor: Colors.border,
        borderRadius: Radius.lg,
        paddingHorizontal: Spacing.md,
        minHeight: 52,
        fontSize: 16,
        color: Colors.text,
        backgroundColor: Colors.surfaceElevated,
    },
    inputError: {
        borderColor: Colors.border,
    },
    inputDisabled: {
        opacity: 0.75,
        backgroundColor: Colors.surface,
    },
    phoneRow: { flexDirection: "row", gap: Spacing.sm, marginTop: Spacing.sm },
    cc: {
        marginTop: Spacing.sm,
        paddingHorizontal: Spacing.md,
        justifyContent: "center",
        borderWidth: 1,
        borderColor: Colors.border,
        borderRadius: Radius.lg,
        minHeight: 52,
        backgroundColor: Colors.surface,
    },
    ccText: { fontWeight: "600", color: Colors.text },
    dlCard: {
        marginTop: Spacing.sm,
        borderWidth: 1,
        borderColor: Colors.border,
        borderRadius: Radius.lg,
        padding: Spacing.md + 2,
        flexDirection: "row",
        alignItems: "center",
        gap: Spacing.sm,
        backgroundColor: Colors.surfaceElevated,
        ...Shadows.floatSm,
    },
    dlDone: { borderColor: Colors.primary, backgroundColor: Colors.primarySoft },
    checkCircle: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: Colors.primary,
        alignItems: "center",
        justifyContent: "center",
    },
    dlTitle: { flex: 1, fontSize: 15, fontWeight: "600", color: Colors.text },
    dlFile: { fontSize: 12, color: Colors.primary, marginTop: 2 },
    uploadBtn: { flexDirection: "row", alignItems: "center", gap: 6 },
    uploadBtnText: { color: Colors.link, fontWeight: "700" },
    note: {
        marginTop: Spacing.lg,
        flexDirection: "row",
        gap: Spacing.sm,
        backgroundColor: Colors.primarySoft,
        borderRadius: Radius.md,
        padding: Spacing.md,
        alignItems: "flex-start",
    },
    noteIcon: { fontSize: 18 },
    noteText: {
        flex: 1,
        fontSize: 14,
        color: Colors.textSecondary,
        lineHeight: 20,
    },
    footer: {
        padding: Spacing.lg,
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: Colors.border,
    },
});
