import { StyleSheet } from "react-native";
import { Colors, Radius, Shadows, Spacing } from "@/config/theme";

export const styles = StyleSheet.create({
    screen: { flex: 1, backgroundColor: Colors.background },
    scroll: { paddingHorizontal: Spacing.lg, paddingBottom: Spacing.xl },
    metaLoading: {
        flexDirection: "row",
        alignItems: "center",
        gap: Spacing.md,
        paddingVertical: Spacing.md,
        marginBottom: Spacing.sm,
    },
    metaLoadingText: { fontSize: 14, color: Colors.textSecondary },
    metaError: {
        padding: Spacing.md,
        backgroundColor: Colors.warningSoft,
        borderRadius: Radius.md,
        marginBottom: Spacing.md,
    },
    metaErrorText: { fontSize: 14, color: Colors.text, marginBottom: Spacing.sm },
    retryBtn: {
        alignSelf: "flex-start",
        paddingVertical: Spacing.sm,
        paddingHorizontal: Spacing.md,
    },
    retryBtnText: { fontWeight: "700", color: Colors.primary },
    fieldLabel: { fontSize: 14, fontWeight: "600", color: Colors.text },
    req: { color: Colors.danger },
    input: {
        marginTop: Spacing.sm,
        borderWidth: 1,
        borderColor: Colors.border,
        borderRadius: Radius.lg,
        paddingHorizontal: Spacing.md,
        minHeight: 52,
        fontSize: 16,
        color: Colors.text,
        backgroundColor: Colors.surfaceElevated,
    },
    inputError: {
        borderColor: Colors.border,
    },
    fieldGroupErrorOutline: {
        borderWidth: 0,
        borderColor: "transparent",
        borderRadius: Radius.lg,
        padding: 0,
    },
    inputLike: {
        marginTop: Spacing.sm,
        borderWidth: 1,
        borderColor: Colors.border,
        borderRadius: Radius.lg,
        paddingHorizontal: Spacing.md,
        minHeight: 52,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        backgroundColor: Colors.surfaceElevated,
    },
    inputDisabled: {
        opacity: 0.8,
    },
    inputText: {
        fontSize: 16,
        color: Colors.text,
        flex: 1,
        paddingRight: Spacing.sm,
    },
    placeholder: { fontSize: 16, color: Colors.textMuted, flex: 1 },
    uploadCard: {
        marginTop: Spacing.sm,
        borderWidth: 1,
        borderColor: Colors.border,
        borderRadius: Radius.lg,
        padding: Spacing.md + 2,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: Spacing.sm,
        backgroundColor: Colors.surfaceElevated,
        ...Shadows.floatSm,
    },
    uploadDone: {
        borderColor: Colors.primary,
        backgroundColor: Colors.primarySoft,
    },
    checkCircle: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: Colors.primary,
        alignItems: "center",
        justifyContent: "center",
    },
    uploadLabel: { fontSize: 15, fontWeight: "600", color: Colors.text, flex: 1 },
    rcUrl: { fontSize: 11, color: Colors.primary, marginTop: 4 },
    uploadBtn: { flexDirection: "row", alignItems: "center", gap: 6 },
    uploadBtnText: { color: Colors.link, fontWeight: "700" },
    typeGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: Spacing.sm,
        marginTop: Spacing.sm,
    },
    typeCard: {
        width: "23%",
        minWidth: 76,
        flexGrow: 1,
        borderWidth: 1,
        borderColor: Colors.border,
        borderRadius: Radius.md,
        padding: Spacing.sm,
        alignItems: "center",
        minHeight: 88,
        justifyContent: "center",
    },
    typeCardActive: {
        borderColor: Colors.primary,
        backgroundColor: Colors.primarySoft,
    },
    typeEmoji: { fontSize: 28 },
    typeLabel: {
        fontSize: 11,
        fontWeight: "600",
        color: Colors.text,
        textAlign: "center",
        marginTop: 4,
    },
    bodyRow: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: Spacing.sm,
        marginTop: Spacing.sm,
    },
    bodyCard: {
        minWidth: "30%",
        flexGrow: 1,
        borderWidth: 1,
        borderColor: Colors.border,
        borderRadius: Radius.md,
        padding: Spacing.md,
        alignItems: "center",
        minHeight: 96,
        justifyContent: "center",
    },
    footer: {
        padding: Spacing.lg,
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: Colors.border,
    },
    dropdown: {
        marginTop: Spacing.sm,
        borderWidth: 1,
        borderColor: Colors.border,
        borderRadius: Radius.lg,
        backgroundColor: Colors.surfaceElevated,
        overflow: "hidden",
        ...Shadows.floatSm,
    },
    dropdownScroll: { maxHeight: 240 },
    dropdownRow: {
        paddingVertical: Spacing.md,
        paddingHorizontal: Spacing.md,
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: Colors.border,
    },
    dropdownRowActive: { backgroundColor: Colors.primarySoft },
    dropdownText: { fontSize: 15, color: Colors.text },
});
