import { StyleSheet } from "react-native";
import { Colors, Radius, Shadows, Spacing, Type } from "@/config/theme";
export const verificationPendingStyles = StyleSheet.create({
    screen: {
        flex: 1,
        backgroundColor: Colors.background,
        paddingHorizontal: Spacing.lg,
    },
    hero: { alignItems: "center" },
    clockCircle: {
        width: 120,
        height: 120,
        borderRadius: 60,
        backgroundColor: Colors.primaryMuted,
        alignItems: "center",
        justifyContent: "center",
        marginBottom: Spacing.lg,
        ...Shadows.floatMd,
    },
    badge: {
        position: "absolute",
        bottom: 8,
        right: 8,
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: Colors.orange,
        alignItems: "center",
        justifyContent: "center",
    },
    title: { ...Type.h1, textAlign: "center" },
    sub: {
        marginTop: Spacing.md,
        fontSize: 15,
        color: Colors.textSecondary,
        textAlign: "center",
        lineHeight: 22,
        paddingHorizontal: Spacing.md,
    },
    subBold: { fontWeight: "800", color: Colors.text },
    card: {
        marginTop: Spacing.xl,
        borderWidth: 1,
        borderColor: Colors.border,
        borderRadius: Radius.xl,
        padding: Spacing.lg,
        backgroundColor: Colors.surfaceElevated,
        ...Shadows.floatMd,
    },
    cardTitle: {
        fontSize: 17,
        fontWeight: "800",
        color: Colors.text,
        marginBottom: Spacing.md,
    },
    stepRow: {
        flexDirection: "row",
        alignItems: "flex-start",
        gap: Spacing.md,
        marginBottom: Spacing.md,
    },
    stepNum: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: Colors.primaryMuted,
        alignItems: "center",
        justifyContent: "center",
    },
    stepNumText: { fontSize: 14, fontWeight: "800", color: Colors.primaryDark },
    stepText: { flex: 1, fontSize: 15, color: Colors.textSecondary, lineHeight: 22 },
    rejectionCard: {
        marginTop: Spacing.lg,
        borderWidth: 1,
        borderColor: Colors.danger,
        borderRadius: Radius.xl,
        padding: Spacing.lg,
        backgroundColor: Colors.surfaceElevated,
        gap: Spacing.sm,
        ...Shadows.floatSm,
    },
    rejectionTitle: {
        fontSize: 16,
        fontWeight: "800",
        color: Colors.danger,
    },
    rejectionReason: {
        fontSize: 14,
        lineHeight: 21,
        color: Colors.textSecondary,
    },
    spacer: { flex: 1 },
    supportBtn: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: Spacing.sm,
        borderWidth: 1,
        borderColor: Colors.border,
        borderRadius: Radius.xl,
        paddingVertical: Spacing.md,
        minHeight: 52,
        marginBottom: Spacing.md,
    },
    supportBtnPressed: { opacity: 0.9 },
    supportText: { fontSize: 16, fontWeight: "700", color: Colors.text },
    demo: {
        textAlign: "center",
        color: Colors.link,
        textDecorationLine: "underline",
        fontSize: 14,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(15, 23, 42, 0.32)",
        justifyContent: "center",
        paddingHorizontal: Spacing.lg,
    },
    modalCard: {
        backgroundColor: Colors.surfaceElevated,
        borderRadius: Radius.xl,
        borderWidth: 1,
        borderColor: Colors.danger,
        padding: Spacing.lg,
        gap: Spacing.md,
        ...Shadows.floatMd,
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: "800",
        color: Colors.danger,
    },
    rejectionPopupCard: {
        backgroundColor: Colors.surfaceElevated,
        borderRadius: Radius.xl,
        borderTopWidth: 3,
        borderTopColor: Colors.danger,
        paddingHorizontal: Spacing.lg,
        paddingTop: 26,
        paddingBottom: 18,
        gap: 12,
        ...Shadows.floatMd,
    },
    rejectionPopupIconWrap: {
        width: 58,
        height: 58,
        borderRadius: 29,
        backgroundColor: Colors.dangerSoft,
        alignItems: "center",
        justifyContent: "center",
        alignSelf: "center",
    },
    rejectionPopupEyebrow: {
        textAlign: "center",
        fontSize: 12,
        fontWeight: "800",
        color: Colors.danger,
        letterSpacing: 1.8,
    },
    rejectionPopupTitle: {
        textAlign: "center",
        fontSize: 24,
        lineHeight: 30,
        fontWeight: "800",
        color: Colors.text,
    },
    modalReason: {
        fontSize: 16,
        lineHeight: 30,
        color: Colors.textSecondary,
        textAlign: "center",
    },
    missingDocCard: {
        borderWidth: 1,
        borderColor: "#F8C7D2",
        backgroundColor: "#FFF8FA",
        borderRadius: Radius.lg,
        padding: Spacing.md,
        gap: Spacing.sm,
    },
    missingDocTitle: {
        fontSize: 12,
        fontWeight: "800",
        color: Colors.danger,
        letterSpacing: 1,
    },
    missingDocRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: Spacing.xs,
    },
    missingDocText: {
        fontSize: 16,
        color: Colors.text,
        fontWeight: "500",
    },
    reuploadBtn: {
        marginTop: Spacing.xs,
        minHeight: 52,
        borderRadius: Radius.lg,
        backgroundColor: Colors.primary,
        alignItems: "center",
        justifyContent: "center",
        flexDirection: "row",
        gap: Spacing.xs,
        ...Shadows.floatSm,
    },
    reuploadBtnPressed: {
        opacity: 0.95,
    },
    reuploadBtnText: {
        color: Colors.white,
        fontSize: 15,
        fontWeight: "700",
    },
    modalDivider: {
        height: StyleSheet.hairlineWidth,
        backgroundColor: Colors.border,
        marginVertical: Spacing.sm,
    },
    modalLogoutRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: Spacing.md,
        paddingVertical: Spacing.md,
        paddingHorizontal: Spacing.md,
        borderRadius: Radius.lg,
        borderWidth: 1,
        borderColor: Colors.danger,
        backgroundColor: Colors.dangerSoft,
    },
    modalLogoutRowPressed: {
        opacity: 0.96,
        backgroundColor: "#FCD6DE",
    },
    modalLogoutIconCircle: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: Colors.surfaceElevated,
        borderWidth: 1,
        borderColor: Colors.danger,
        alignItems: "center",
        justifyContent: "center",
    },
    modalLogoutTextBlock: {
        flex: 1,
        gap: 2,
    },
    modalLogoutTitle: {
        fontSize: 16,
        fontWeight: "700",
        color: Colors.danger,
        letterSpacing: 0.15,
    },
    modalLogoutHint: {
        fontSize: 13,
        lineHeight: 18,
        color: Colors.textSecondary,
        fontWeight: "500",
    },
    modalLaterBtn: {
        alignItems: "center",
        paddingVertical: Spacing.xs,
    },
    modalLaterText: {
        fontSize: 14,
        color: Colors.link,
        textDecorationLine: "underline",
    },
    secondaryActionBtn: {
        borderWidth: 1,
        borderColor: Colors.border,
        borderRadius: Radius.lg,
        minHeight: 52,
        alignItems: "center",
        justifyContent: "center",
        flexDirection: "row",
        gap: Spacing.xs,
        backgroundColor: Colors.surfaceElevated,
    },
    secondaryActionText: {
        fontSize: 16,
        fontWeight: "500",
        color: Colors.textSecondary,
    },
    modalLogoutTextBtn: {
        alignSelf: "flex-start",
        paddingVertical: Spacing.xs,
        paddingHorizontal: Spacing.xs,
    },
    modalLogoutText: {
        fontSize: 14,
        fontWeight: "500",
        color: Colors.danger,
    },
    rejectionPopupFooterText: {
        marginTop: 2,
        textAlign: "center",
        color: "#C4C7CC",
        fontSize: 12,
        fontWeight: "500",
    },
    logoutConfirmCard: {
        backgroundColor: Colors.surfaceElevated,
        borderRadius: Radius.xl,
        borderWidth: 1,
        borderColor: Colors.border,
        padding: Spacing.lg,
        gap: Spacing.md,
        ...Shadows.floatMd,
    },
    logoutConfirmTitle: {
        fontSize: 20,
        fontWeight: "800",
        color: Colors.text,
        textAlign: "center",
    },
    logoutConfirmMessage: {
        fontSize: 15,
        lineHeight: 22,
        color: Colors.textSecondary,
        textAlign: "center",
    },
    logoutConfirmActions: {
        marginTop: Spacing.sm,
        gap: Spacing.sm,
    },
    logoutConfirmNoBtn: {
        borderColor: Colors.border,
    },
    logoutConfirmYesBtn: {
        backgroundColor: Colors.danger,
    },
});
